# Workflow for CRAN submission on release
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      submit_to_cran:
        description: 'Submit to CRAN?'
        required: true
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

name: CRAN-submission

jobs:
  cran-submission:
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools, any::rhub, any::rcmdcheck
          needs: check

      - name: Check package
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning")
        shell: Rscript {0}

      - name: Build source package
        run: |
          dir.create("submission", showWarnings = FALSE)
          pkg_built <- pkgbuild::build(dest_path = "submission", binary = FALSE)
          cat("PKG_BUILT=", pkg_built, "\n", file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        shell: Rscript {0}

      - name: Upload source package
        uses: actions/upload-artifact@v4
        with:
          name: cran-submission
          path: submission/

      - name: Comment on release
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.release.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📦 **CRAN Submission Ready!**\n\nThe package has passed R CMD check and a source package has been built. Download the `cran-submission` artifact and submit manually to CRAN.\n\n**Next steps:**\n1. Download the source package from the workflow artifacts\n2. Submit to CRAN via [web interface](https://cran.r-project.org/submit.html)\n3. Wait for CRAN feedback and address any issues'
            })